#!/usr/bin/env bash
# Emit src/build_info.zig with git commit and build date for About + CLI metadata.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

commit="unknown"
if git rev-parse --short=6 HEAD >/dev/null 2>&1; then
  commit="$(git rev-parse --short=6 HEAD)"
  if ! git diff --quiet --ignore-submodules HEAD 2>/dev/null; then
    commit="${commit}-dirty"
  fi
fi

build_date="$(date -u +%Y-%m-%d)"

cat > src/build_info.zig <<EOF
// Generated by scripts/gen-build-info.sh — do not edit.
pub const commit = "${commit}";
pub const build_date = "${build_date}";
EOF
