const std = @import("std");
const game_engine = @import("game_engine.zig");
const config = @import("config.zig");
const puzzle_gen = @import("puzzle_gen.zig");
const command = @import("command/parse.zig");

const disambiguate = @import("command/disambiguate.zig");
const legend = @import("command/legend.zig");

const mypath = @import("command/path.zig");


pub fn Sudoku(comptime R: type) type {
    return struct {
        engine: game_engine.GameEngine,
        cfg: config.Config,
        io: std.Io,
        renderer: *R,
        pub fn init(cfg: config.Config, _r: *R, io: std.Io) anyerror!@This() {
            const puzzle_str = puzzle_gen.PuzzleGen.generate(cfg.difficulty);
            return @This(){
                .renderer = _r,
                .io = io,
                .cfg = cfg,
                .engine = try game_engine.GameEngine.init(puzzle_str, io),
            };
        }

        /// Read a line from stdin excluding newline at the end
        fn readLine(reader: anytype) anyerror![]const u8 {
            return try reader.takeDelimiter('\n') orelse return error.ReadEOF;
        }

        /// Show an error message and wait for Enter to continue.
        fn waitAck(self: *@This(), writer: anytype, reader: anytype, msg: []const u8) anyerror!void {
            _ = self;
            try writer.print("{s}\n", .{msg});
            try writer.print("Press Enter to continue... ", .{});

            _ = try readLine(reader);
        }

        /// Print the command legend line after a board render.
        fn printLegend(self: *@This(), writer: anytype) !void {
            const avail = self.engine.getAvailableCommands();

            var names: [8][]const u8 = undefined;
            const count = avail.getNames(&names);

            var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
            defer arena.deinit();

            const entries = try disambiguate.getMinimumPrefixes(arena.allocator(), names[0..count]);
            const str = try legend.formatLegend(arena.allocator(), entries);

            try writer.print("  Command: {s}\n", .{str});
        }

        /// Handle a dispatched Event. Returns true when is_quit flag is set.
        /// (the 'isDone' signal is only generated by handleResult — e.g. .quit).
        fn handleEvent(self: *@This(), out: anytype, in_: anytype, event: game_engine.Event) anyerror!bool {
            switch (event) {
                .ok => |ev| {
                    if (ev.is_quit) return true;

                    if (ev.msg) |m| try out.print("{s}\n", .{m});
                    try self.renderer.render(ev.board_view, null);
                    try self.printLegend(out);
                    return false;
                },
                .error_msg => |msg| {
                    try self.waitAck(out, in_, msg);
                    return false;
                },
            }
        }

        /// Handle one parsed result. Returns true when the command loop should end.
        fn handleResult(self: *@This(), out: anytype, in_: anytype, result: command.ParseCommandResult) anyerror!bool {
            switch (result) {
                .error_msg => |msg| {
                    try self.waitAck(out, in_, msg);
                    return false;
                },
                .valid => |cmd| {
                    const event = self.engine.exec(cmd) catch |err| {
                        var buf: [80]u8 = undefined;
                        const msg = std.fmt.bufPrint(&buf, "exec failed: {s}", .{@errorName(err)}) catch unreachable;
                        try self.waitAck(out, in_, msg);
                        return false;
                    };
                    return self.handleEvent(out, in_, event) catch |err| {
                        var buf: [80]u8 = undefined;
                        const msg = std.fmt.bufPrint(&buf, "handleEvent failed: {s}", .{@errorName(err)}) catch unreachable;
                        try self.waitAck(out, in_, msg);
                        return false;
                    };
                },
            }
        }

        /// Prompt the user, read a line, parse it, and dispatch. Returns true on quit.
        fn promptForAndRunCommand(self: *@This(), out: anytype, in_: anytype) anyerror!bool {
            try out.print("> ", .{});

            const line = try readLine(in_);
            if (line.len == 0) return false; // empty input -> stay in loop

            const tokens = std.mem.trim(u8, line, &std.ascii.whitespace);
            // Build available command names for context-aware prefix dispatch
            const avail = self.engine.getAvailableCommands();

            var names: [8][]const u8 = undefined;
            const count = avail.getNames(&names);

            const result = command.parseWithCommands(tokens, names[0..count]);

            // First save: prompt for a filename.
            switch (result) {
                .valid => |cmd| {
                    switch (cmd) {
                        .save => {
                            if (self.engine.filename == null) {
                                const gpa = std.heap.page_allocator;

                                // Resolve data dir first so we can show the full default path.
                                if (self.engine.data_dir == null) {
                                    self.engine.data_dir = try mypath.getDataDir(gpa, self.io);
                                }

                                const resolved_default = try mypath.resolveSavePath(
                                     gpa,
                                     self.engine.data_dir.?,
                                     ".sudoku_save.sud",
                                );
                                defer gpa.free(resolved_default);

                                try out.print("Save to [{s}]: ", .{resolved_default});

                                const save_input = try readLine(in_);
                                const trimmed = std.mem.trim(u8, save_input, &std.ascii.whitespace);
                                const chosen = if (trimmed.len > 0)
                                    trimmed
                                else
                                    ".sudoku_save.sud";
                                self.engine.filename = try gpa.dupe(u8, chosen);
                            }
                        },
                        else => {},
                    }
                    },
                .error_msg => {},
            }

            return try self.handleResult(out, in_, result);
        }

        /// Read → Parse → Loop command interface.
        pub fn run(self: *@This()) anyerror!void {
            var stdout_writer = std.Io.File.stdout().writer(self.io, &.{});
            const out = &stdout_writer.interface;
            var stdin_buf: [1024]u8 = undefined;
            var stdin_reader = std.Io.File.stdin().reader(self.io, &stdin_buf);
            const in_ = &stdin_reader.interface;

            // Initial render — show starting board via Event seam
            try self.renderer.render(self.engine.eventBoard(), null);
            try self.printLegend(out);

            var isDone: bool = false;
            while (!isDone) {
                isDone = try self.promptForAndRunCommand(out, in_);
            }
        }
    };
}

const mock_renderer = @import("renderer/mock/mock_renderer.zig");
const board = @import("board.zig");
const cell = @import("cell.zig");

test "Sudoku.init uses config difficulty to build the board" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);

    // The hard puzzle has different given cells than the default puzzle.
    // For example, hard[0] is '0' (empty) whereas default[0] is '6'.
    // If init used PuzzleGen.default() instead of cfg.difficulty, cell (0,0) would be six.
    try std.testing.expect(!sudoku.engine.board.isGiven(0, 0));
}

test "Sudoku.init with .medium difficulty loads medium puzzle" {
    const cfg: config.Config = .{
        .difficulty = .medium,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);

    // medium[0] is '8' (given) — hard and easy both have '0' here.
    try std.testing.expect(sudoku.engine.board.isGiven(0, 0));
}

test "legend pipeline: fresh engine produces (F)ill (C)lear (Q)uit" {
    var engine = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.default(), std.testing.io);
    defer engine.deinit();

    // Fresh engine has only fill, clear, quit (no undo/redo)
    const avail = engine.getAvailableCommands();
    try std.testing.expect(avail.fill);
    try std.testing.expect(avail.clear);
    try std.testing.expect(avail.quit);
    try std.testing.expect(!avail.undo);
    try std.testing.expect(!avail.redo);

    // Build command name list from AvailableCommands
    var names: [5][]const u8 = undefined;
    var count: usize = 0;
    if (avail.fill) {
        names[count] = "Fill";
        count += 1;
    }
    if (avail.clear) {
        names[count] = "Clear";
        count += 1;
    }
    if (avail.quit) {
        names[count] = "Quit";
        count += 1;
    }
    if (avail.undo) {
        names[count] = "Undo";
        count += 1;
    }
    if (avail.redo) {
        names[count] = "Redo";
        count += 1;
    }

    // Disambiguate + format
    const entries = try disambiguate.getMinimumPrefixes(std.testing.allocator, names[0..count]);
    defer std.testing.allocator.free(entries);

    const result = try legend.formatLegend(std.testing.allocator, entries);
    defer std.testing.allocator.free(result);

    try std.testing.expectEqualStrings("(F)ill (C)lear (Q)uit", result);
}

test "legend pipeline: after fill then undo shows Undo AND Redo" {
    var engine = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.default(), std.testing.io);
    defer engine.deinit();

    // Fill a cell to enable Undo
    _ = try engine.exec(command.Command{
        .fill = command.FillData{ .row = 0, .col = 2, .digit = cell.CellValue.seven },
    });

    // Undo to populate both Undo and Redo availability... wait — after undo only Redo.
    // Let me test: fill TWO cells, undo ONE → both Undo AND Redo available.
    _ = try engine.exec(command.Command{
        .fill = command.FillData{ .row = 0, .col = 3, .digit = cell.CellValue.one },
    });

    // Now undo once — pointer goes from 2 to 1
    _ = try engine.exec(command.Command{ .undo = {} });

    const avail = engine.getAvailableCommands();
    try std.testing.expect(avail.fill);
    try std.testing.expect(avail.clear);
    try std.testing.expect(avail.quit);
    try std.testing.expect(avail.undo);
    try std.testing.expect(avail.redo);

    var names: [5][]const u8 = undefined;
    var count: usize = 0;
    if (avail.fill) {
        names[count] = "Fill";
        count += 1;
    }
    if (avail.clear) {
        names[count] = "Clear";
        count += 1;
    }
    if (avail.quit) {
        names[count] = "Quit";
        count += 1;
    }
    if (avail.undo) {
        names[count] = "Undo";
        count += 1;
    }
    if (avail.redo) {
        names[count] = "Redo";
        count += 1;
    }

    const entries = try disambiguate.getMinimumPrefixes(std.testing.allocator, names[0..count]);
    defer std.testing.allocator.free(entries);

    const result = try legend.formatLegend(std.testing.allocator, entries);
    defer std.testing.allocator.free(result);

    // With all 5 commands, each prefix is 1 char (F/C/Q/U/R all distinct)
    try std.testing.expectEqualStrings("(F)ill (C)lear (Q)uit (U)ndo (R)edo", result);
}
test "legend pipeline: fresh engine includes Save and Open in legend" {
    var engine = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.default(), std.testing.io);
    defer engine.deinit();

    const avail = engine.getAvailableCommands();

    // Build command name list including save/open
    var names: [8][]const u8 = undefined;
    var count: usize = 0;
    if (avail.fill) {
        names[count] = "Fill";
        count += 1;
    }
    if (avail.clear) {
        names[count] = "Clear";
        count += 1;
    }
    if (avail.quit) {
        names[count] = "Quit";
        count += 1;
    }
    if (avail.save) {
        names[count] = "Save";
        count += 1;
    }
    if (avail.open) {
        names[count] = "Open";
        count += 1;
    }


    if (avail.new) {
        names[count] = "New";
        count += 1;
    }


    const entries = try disambiguate.getMinimumPrefixes(std.testing.allocator, names[0..count]);
    defer std.testing.allocator.free(entries);

    const result = try legend.formatLegend(std.testing.allocator, entries);
    defer std.testing.allocator.free(result);

    // Fresh engine has 7 available commands (fill/clear/quit always true, save/open always true). Undo/redo start false.
    try std.testing.expect(avail.fill);
    try std.testing.expect(avail.clear);
    try std.testing.expect(avail.quit);
    try std.testing.expect(!avail.undo);
    try std.testing.expect(!avail.redo);
    try std.testing.expect(avail.save);
    try std.testing.expect(avail.open);

    // Check the entries directly — same source of truth as formatLegend.
    // Don't assert on formatted strings; use the disambiguation result.

    var found_save = false;
    var found_open = false;
    for (entries) |entry| {
        if (std.mem.eql(u8, entry.command, "Save")) {
            found_save = true;
        }
        if (std.mem.eql(u8, entry.command, "Open")) {
            found_open = true;
        }
    }
    try std.testing.expect(found_save);
    try std.testing.expect(found_open);
}

// Step 11 — mock I/O for full-seam integration test through promptForAndRunCommand.

const MockReader = struct {
    responses: []const []const u8,
    idx: usize,

    pub fn initMockReader(responses: []const []const u8) MockReader {
        return .{
            .responses = responses,
            .idx = 0,
        };
    }

    /// Match Io.Reader.interface.takeDelimiter signature: !?[]u8
    pub fn takeDelimiter(self: *MockReader, delimiter: u8) !?[]u8 {
        _ = delimiter;
        if (self.idx >= self.responses.len) return null;
        const resp = self.responses[self.idx];
        return @constCast(resp);
    }
};

const MockWriter = struct {
    buffer: [2048]u8,
    pos: usize,

    pub fn initMockWriter() MockWriter {
        var buf: [2048]u8 = undefined;
        @memset(&buf, 0);
        return .{
            .buffer = buf,
            .pos = 0,
        };
    }

    pub fn getWritten(self: *const MockWriter) []const u8 {
        return self.buffer[0..self.pos];
    }

    pub fn print(self: *MockWriter, comptime fmt: []const u8, args: anytype) !void {
        const written = try std.fmt.bufPrint(self.buffer[self.pos..], fmt, args);
        self.pos += written.len;
    }
};


  // Step 7 test placeholder
test "Sudoku stores io field during init" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku_instance = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku_instance.engine.deinit();
    _ = sudoku_instance.io;
}
test "full seam: f A3 4 -> prefix dispatch -> fill (0,2)=four -> render+legend w/ Undo" {
    // Arrange: fresh engine via Sudoku.init gives Fill/Clear/Quit only.
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    // Feed: "f A3 4" as the single typed command.
    var mr = MockReader.initMockReader(&[_][]const u8{"f A3 4"});
    var mw = MockWriter.initMockWriter();

    // Act: one cycle of prompt -> parse -> dispatch -> exec -> render -> legend
    _ = try sudoku.promptForAndRunCommand(&mw, &mr);

    // Assert (a): engine has undo available after mutation.
    {
        const avail = sudoku.engine.getAvailableCommands();
        try std.testing.expect(avail.undo);
    }

    // Assert (b): renderer was called, cell at chess coord A3 -> row 2, col 0 is four.
    {
        try std.testing.expect(mock.call_count > 0);
        const rendered = mock.last_rendered_cells orelse unreachable;
        try std.testing.expectEqual(cell.CellValue.four, rendered[2][0]);
    }

    // DEBUG: print mock writer output so we can see what's missing
    // Assert (c): legend shows Undo available now that a mutation occurred.
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "Command:") != null);
        // Legend formats as "(U)ndo" not plain "Undo" — search formatted form
        try std.testing.expect(std.mem.indexOf(u8, output, "(U)ndo") != null);
    }
}

// Step 7 — integration test: OPEN command wired through handleResult/promptForAndRunCommand

test "full seam: open loads saved game" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    const tmp_path = "/tmp/sudoku_tdd_open_test.sud";
    defer std.Io.Dir.deleteFileAbsolute(std.testing.io, tmp_path) catch {};

    // Create fresh engine with known state before mutations
    var original = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.hard(), std.testing.io);
    defer original.deinit();

    // Save pristine (mutated-then-undone) state to disk
    // Mutate and undo to exercise history round-trip
    _ = try original.exec(command.Command{
        .fill = command.FillData{ .row = 1, .col = 1, .digit = cell.CellValue.one },
    });
    _ = try original.exec(command.Command{ .undo = {} });
    try original.saveGame(std.testing.io, tmp_path);

    // Now open through handleResult to prove the handler is wired
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    // Fill a cell that was empty in the saved state — this proves divergence from saved state
    _ = try sudoku.engine.exec(command.Command{
        .fill = command.FillData{ .row = 1, .col = 1, .digit = cell.CellValue.seven },
    });
    try std.testing.expectEqual(cell.CellValue.seven, sudoku.engine.eventBoard().get(1, 1));

    // Parse open command and dispatch via handleResult seam
    var mw = MockWriter.initMockWriter();
    var mr = MockReader.initMockReader(&[_][]const u8{});
    const parsed_open = command.parse("open " ++ tmp_path);
    const is_done = try sudoku.handleResult(&mw, &mr, parsed_open);

    // Assert: loop continues (isDone = false)
    try std.testing.expect(!is_done);

    // Assert: stub message no longer present — handler calls openGame instead of placeholder print
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "not yet implemented") == null);
    }

    // Assert: engine state restored to saved version (B2 should be back to empty, not seven)
    try std.testing.expectEqual(cell.CellValue.zero, sudoku.engine.eventBoard().get(1, 1));
}

// Step 10 — Save/Open must route through handleEvent() for feedback + re-render

test "handleResult: save success produces status message, re-render, legend refresh" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    const call_count_before: usize = mock.call_count;

    // No MockReader needed — save handler uses default filename (no prompt)
    var mw = MockWriter.initMockWriter();
var mr = MockReader.initMockReader(&[_][]const u8{});

    const parsed_save = command.parse("save");
    _ = sudoku.handleResult(&mw, &mr, parsed_save) catch |err| {
        // I/O failure (no $HOME, dir can't be created, etc.) is acceptable in test env
        try std.testing.expect(err == error.FileNotFound or err == error.EnvironmentVariableMissing);
        return;
    };

    // Assert: status message confirming the save
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "saved") != null or
            std.mem.indexOf(u8, output, "Saved") != null);
    }

    // Assert: renderer called (board re-rendered after save)
    try std.testing.expect(mock.call_count > call_count_before);

    // Assert: legend refreshed on writer
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "Command:") != null);
    }
}

test "handleResult: open success produces status message, re-render, and legend refresh" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };

    // Create a save file first
    var original = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.hard(), std.testing.io);
    defer original.deinit();
    const tmp_path = "/tmp/sudoku_seam_open_feedback_test.sud";
    defer std.Io.Dir.deleteFileAbsolute(std.testing.io, tmp_path) catch {};
    try original.saveGame(std.testing.io, tmp_path);

    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    const call_count_before: usize = mock.call_count;

    var mw = MockWriter.initMockWriter();
    var mr = MockReader.initMockReader(&[_][]const u8{});

    const parsed_open = command.parse("open " ++ tmp_path);
    _ = try sudoku.handleResult(&mw, &mr, parsed_open);

    // Assert: status message confirming the open
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "opened") != null or
            std.mem.indexOf(u8, output, "Opened") != null);
    }

    // Assert: renderer called (board re-rendered after open)
    try std.testing.expect(mock.call_count > call_count_before);

    // Assert: legend refreshed
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "Command:") != null);
    }
}

// Step 11 — Open with relative path must not crash (resolved against data dir)

test "handleResult: open with relative path resolves without panic" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };

    // Create save file at some known absolute path first
    var original = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.hard(), std.testing.io);
    defer original.deinit();
    const abs_path = "/tmp/sudoku_seam_relative_test.sud";
    defer std.Io.Dir.deleteFileAbsolute(std.testing.io, abs_path) catch {};
    try original.saveGame(std.testing.io, abs_path);

    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    var mw = MockWriter.initMockWriter();
var mr = MockReader.initMockReader(&[_][]const u8{"\n"});

    const parsed_open = command.parse("open somename.sud");
    _ = sudoku.handleResult(&mw, &mr, parsed_open) catch |err| {
        // FileNotFound is acceptable — file doesn't exist yet at resolved path.
        // The bug is a PANIC from openFileAbsolute on relative paths; an error return proves that's fixed.
        try std.testing.expect(err == error.FileNotFound);
    };

    // We got here without panic — test passes
}

// Step 12 — Save/Open goes through exec() now (default filename, no prompt)

test "handleResult: save uses default filename and returns success" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    var mw = MockWriter.initMockWriter();
var mr = MockReader.initMockReader(&[_][]const u8{});

    const parsed_save = command.parse("save");
            _ = sudoku.handleResult(&mw, &mr, parsed_save) catch |err| {
        try std.testing.expect(err == error.FileNotFound or err == error.EnvironmentVariableMissing);
        return;
    };


    // Assert: save succeeded with feedback, no prompt needed
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "saved") != null or
            std.mem.indexOf(u8, output, "Saved") != null);
        // No filename prompt in the new architecture
        try std.testing.expect(std.mem.indexOf(u8, output, "Save to") == null);
    }
}
// Step 12b — Subsequent saves reuse last filename, give feedback without prompting

test "handleResult: subsequent save reuses previous filename with feedback" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };

    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock, std.testing.io);
    defer sudoku.engine.deinit();

    // First save sets the default filename (no prompt in new flow)
    var mr = MockReader.initMockReader(&[_][]const u8{"\n", "\n"});

    var mw1 = MockWriter.initMockWriter();
    const parsed_save_1 = command.parse("save");
            _ = try sudoku.handleResult(&mw1, &mr, parsed_save_1);

    // Second save reuses filename — no prompt, just confirmation
    var mw2 = MockWriter.initMockWriter();
    const call_count_before = mock.call_count;

    const parsed_save_2 = command.parse("save");
            _ = try sudoku.handleResult(&mw2, &mr, parsed_save_2);

    // Assert: status message confirming the second save
    {
        const output = mw2.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "saved") != null or
            std.mem.indexOf(u8, output, "Saved") != null);
    }

    // Assert: board re-rendered + legend refreshed via handleEvent routing
    try std.testing.expect(mock.call_count > call_count_before);
}
