const std = @import("std");
const game_engine = @import("game_engine.zig");
const config = @import("config.zig");
const puzzle_gen = @import("puzzle_gen.zig");
const command = @import("command.zig");

const disambiguate = @import("disambiguate.zig");
const legend = @import("legend.zig");
pub fn Sudoku(comptime R: type) type {
    return struct {
        engine: game_engine.GameEngine,
        cfg: config.Config,

        pub fn init(cfg: config.Config, _r: *R) anyerror!@This() {
            _ = _r; // not forwarded to engine anymore — renderer lives in run()
            const puzzle_str = puzzle_gen.PuzzleGen.generate(cfg.difficulty);
            const engine = try game_engine.GameEngine.init(puzzle_str);
            return .{
                .engine = engine,
                .cfg = cfg,
            };
        }

        /// Read a line from stdin excluding newline at the end
        fn readLine(reader: anytype) anyerror![]const u8 {
            return try reader.takeDelimiter('\n') orelse return error.ReadEOF;
        }

        /// Show an error message and wait for Enter to continue.
        fn waitAck(self: *@This(), writer: anytype, reader: anytype, msg: []const u8) anyerror!void {
            _ = self;
            try writer.print("{s}\n", .{msg});
            try writer.print("Press Enter to continue... ", .{});

            _ = try readLine(reader);
        }

        /// Print the command legend line after a board render.
        fn printLegend(self: *@This(), writer: anytype) !void {
            const avail = self.engine.getAvailableCommands();

            var names: [5][]const u8 = undefined;
            var count: usize = 0;
            if (avail.fill) { names[count] = "Fill"; count += 1; }
            if (avail.clear) { names[count] = "Clear"; count += 1; }
            if (avail.quit) { names[count] = "Quit"; count += 1; }
            if (avail.undo) { names[count] = "Undo"; count += 1; }
            if (avail.redo) { names[count] = "Redo"; count += 1; }

            var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
            defer arena.deinit();

            const entries = try disambiguate.getMinimumPrefixes(arena.allocator(), names[0..count]);
            const str = try legend.formatLegend(arena.allocator(), entries);

            try writer.print("  Command: {s}\n", .{str});
        }

        /// Handle a dispatched Event. Always returns false to keep the loop going
        /// (the 'isDone' signal is only generated by handleResult — e.g. .quit).
        fn handleEvent(self: *@This(), out: anytype, in_: anytype, renderer: anytype, event: game_engine.Event) anyerror!bool {
            switch (event) {
                .ok => |ev| {
                    if (ev.msg) |m| try out.print("{s}\n", .{m});
                    try renderer.render(ev.board_view);
                    try self.printLegend(out);
                    return false;
                },
                .error_msg => |msg| {
                    try self.waitAck(out, in_, msg);
                    return false;
                },
            }
        }

        /// Handle one parsed result. Returns true when the command loop should end.
        fn handleResult(self: *@This(), out: anytype, in_: anytype, renderer: anytype, result: command.ParseCommandResult) anyerror!bool {
            switch (result) {
                .error_msg => |msg| {
                    try self.waitAck(out, in_, msg);
                    return false; // continue looping
                },
                .valid => |cmd| {
                    if (cmd == .quit) return true;

                    const event = try self.engine.exec(cmd);
                    return try self.handleEvent(out, in_, renderer, event);
                },
            }
        }

        /// Prompt the user, read a line, parse it, and dispatch. Returns true on quit.
        fn promptForAndRunCommand(self: *@This(), out: anytype, in_: anytype, renderer: anytype) anyerror!bool {
            try out.print("> ", .{});

            const line = try readLine(in_);
            if (line.len == 0) return false; // empty input -> stay in loop

            const tokens = std.mem.trim(u8, line, &std.ascii.whitespace);

            // Build available command names for context-aware prefix dispatch
            const avail = self.engine.getAvailableCommands();
            var names: [5][]const u8 = undefined;
            var count: usize = 0;
            if (avail.fill) { names[count] = "Fill"; count += 1; }
            if (avail.clear) { names[count] = "Clear"; count += 1; }
            if (avail.quit) { names[count] = "Quit"; count += 1; }
            if (avail.undo) { names[count] = "Undo"; count += 1; }
            if (avail.redo) { names[count] = "Redo"; count += 1; }

            const result = command.parseWithCommands(tokens, names[0..count]);
            return try self.handleResult(out, in_, renderer, result);
        }

        /// Read → Parse → Loop command interface.
        pub fn run(self: *@This(), io: std.Io, renderer: anytype) anyerror!void {
            var stdout_writer = std.Io.File.stdout().writer(io, &.{});
            const out = &stdout_writer.interface;
            var stdin_buf: [1024]u8 = undefined;
            var stdin_reader = std.Io.File.stdin().reader(io, &stdin_buf);
            const in_ = &stdin_reader.interface;

            // Initial render — show starting board via Event seam
            try renderer.render(self.engine.eventBoard());
            try self.printLegend(out);

            var isDone: bool = false;
            while (!isDone) {
                isDone = try self.promptForAndRunCommand(out, in_, renderer);
            }
        }
    };
}

const mock_renderer = @import("mock_renderer.zig");
const board = @import("board.zig");
const cell = @import("cell.zig");

test "Sudoku.init uses config difficulty to build the board" {
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock);

    // The hard puzzle has different given cells than the default puzzle.
    // For example, hard[0] is '0' (empty) whereas default[0] is '6'.
    // If init used PuzzleGen.default() instead of cfg.difficulty, cell (0,0) would be six.
    try std.testing.expect(!sudoku.engine.board.isGiven(0, 0));
}

test "Sudoku.init with .medium difficulty loads medium puzzle" {
    const cfg: config.Config = .{
        .difficulty = .medium,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock);

    // medium[0] is '8' (given) — hard and easy both have '0' here.
    try std.testing.expect(sudoku.engine.board.isGiven(0, 0));
}

test "legend pipeline: fresh engine produces (F)ill (C)lear (Q)uit" {
    var engine = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.default());
    defer engine.deinit();

    // Fresh engine has only fill, clear, quit (no undo/redo)
    const avail = engine.getAvailableCommands();
    try std.testing.expect(avail.fill);
    try std.testing.expect(avail.clear);
    try std.testing.expect(avail.quit);
    try std.testing.expect(!avail.undo);
    try std.testing.expect(!avail.redo);

    // Build command name list from AvailableCommands
    var names: [5][]const u8 = undefined;
    var count: usize = 0;
    if (avail.fill) { names[count] = "Fill"; count += 1; }
    if (avail.clear) { names[count] = "Clear"; count += 1; }
    if (avail.quit) { names[count] = "Quit"; count += 1; }
    if (avail.undo) { names[count] = "Undo"; count += 1; }
    if (avail.redo) { names[count] = "Redo"; count += 1; }

    // Disambiguate + format
    const entries = try disambiguate.getMinimumPrefixes(std.testing.allocator, names[0..count]);
    defer std.testing.allocator.free(entries);

    const result = try legend.formatLegend(std.testing.allocator, entries);
    defer std.testing.allocator.free(result);

    try std.testing.expectEqualStrings("(F)ill (C)lear (Q)uit", result);
}

test "legend pipeline: after fill then undo shows Undo AND Redo" {
    var engine = try game_engine.GameEngine.init(puzzle_gen.PuzzleGen.default());
    defer engine.deinit();

    // Fill a cell to enable Undo
    _ = try engine.exec(command.Command{
        .fill = command.FillData{ .row = 0, .col = 2, .digit = cell.CellValue.seven },
    });

    // Undo to populate both Undo and Redo availability... wait — after undo only Redo.
    // Let me test: fill TWO cells, undo ONE → both Undo AND Redo available.
    _ = try engine.exec(command.Command{
        .fill = command.FillData{ .row = 0, .col = 3, .digit = cell.CellValue.one },
    });

    // Now undo once — pointer goes from 2 to 1
    _ = try engine.exec(command.Command{ .undo = {} });

    const avail = engine.getAvailableCommands();
    try std.testing.expect(avail.fill);
    try std.testing.expect(avail.clear);
    try std.testing.expect(avail.quit);
    try std.testing.expect(avail.undo);
    try std.testing.expect(avail.redo);

    var names: [5][]const u8 = undefined;
    var count: usize = 0;
    if (avail.fill) { names[count] = "Fill"; count += 1; }
    if (avail.clear) { names[count] = "Clear"; count += 1; }
    if (avail.quit) { names[count] = "Quit"; count += 1; }
    if (avail.undo) { names[count] = "Undo"; count += 1; }
    if (avail.redo) { names[count] = "Redo"; count += 1; }

    const entries = try disambiguate.getMinimumPrefixes(std.testing.allocator, names[0..count]);
    defer std.testing.allocator.free(entries);

    const result = try legend.formatLegend(std.testing.allocator, entries);
    defer std.testing.allocator.free(result);

    // With all 5 commands, each prefix is 1 char (F/C/Q/U/R all distinct)
    try std.testing.expectEqualStrings("(F)ill (C)lear (Q)uit (U)ndo (R)edo", result);
}

// Step 11 — mock I/O for full-seam integration test through promptForAndRunCommand.

const MockReader = struct {
    responses: []const []const u8,
    idx: usize,

    pub fn initMockReader(responses: []const []const u8) MockReader {
        return .{
            .responses = responses,
            .idx = 0,
        };
    }

    /// Match Io.Reader.interface.takeDelimiter signature: !?[]u8
    pub fn takeDelimiter(self: *MockReader, delimiter: u8) !?[]u8 {
        _ = delimiter;
        if (self.idx >= self.responses.len) return null;
        const resp = self.responses[self.idx];
        return @constCast(resp);
    }
};

const MockWriter = struct {
    buffer: [2048]u8,
    pos: usize,

    pub fn initMockWriter() MockWriter {
        var buf: [2048]u8 = undefined;
        @memset(&buf, 0);
        return .{
            .buffer = buf,
            .pos = 0,
        };
    }

    pub fn getWritten(self: *const MockWriter) []const u8 {
        return self.buffer[0..self.pos];
    }

    pub fn print(self: *MockWriter, comptime fmt: []const u8, args: anytype) !void {
        const written = try std.fmt.bufPrint(self.buffer[self.pos..], fmt, args);
        self.pos += written.len;
    }
};

test "full seam: f A3 4 -> prefix dispatch -> fill (0,2)=four -> render+legend w/ Undo" {
    // Arrange: fresh engine via Sudoku.init gives Fill/Clear/Quit only.
    const cfg: config.Config = .{
        .difficulty = .hard,
        .preferred_renderer = .ascii_ansi,
        .fallback_renderer = .ascii_ansi,
    };
    var mock = mock_renderer.MockRenderer.init();
    var sudoku = try Sudoku(mock_renderer.MockRenderer).init(cfg, &mock);
    defer sudoku.engine.deinit();

    // Feed: "f A3 4" as the single typed command.
    var mr = MockReader.initMockReader(&[_][]const u8{ "f A3 4" });
    var mw = MockWriter.initMockWriter();

    // Act: one cycle of prompt -> parse -> dispatch -> exec -> render -> legend
    _ = try sudoku.promptForAndRunCommand(&mw, &mr, &mock);

    // Assert (a): engine has undo available after mutation.
    {
        const avail = sudoku.engine.getAvailableCommands();
        try std.testing.expect(avail.undo);
    }

    // Assert (b): renderer was called, cell at chess coord A3 -> row 2, col 0 is four.
    {
        try std.testing.expect(mock.call_count > 0);
        const rendered = mock.last_rendered_cells orelse unreachable;
        try std.testing.expectEqual(cell.CellValue.four, rendered[2][0]);
    }

    // DEBUG: print mock writer output so we can see what's missing
    // Assert (c): legend shows Undo available now that a mutation occurred.
    {
        const output = mw.getWritten();
        try std.testing.expect(std.mem.indexOf(u8, output, "Command:") != null);
        // Legend formats as "(U)ndo" not plain "Undo" — search formatted form
        try std.testing.expect(std.mem.indexOf(u8, output, "(U)ndo") != null);
    }
}
